### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by yunkuangao** [NWYLZW/openman#1]

**Comment by NWYLZW** [comment]
现在还不能很方便的使用，不过最近我会提供更多的能力
目前只能运行对应的单测获取你想要的内容

<img width="851" alt="image" src="https://user-images.githubusercontent.com/51358815/206137735-567c3ef3-93bd-4990-9ca0-b5ce4ac578c6.png">

**Comment by yunkuangao** [comment]
6666
